/** @type {import('tailwindcss').Config} */
export default {
    darkMode: 'class',
    content: [
        './resources/**/*.blade.php',
        './resources/**/*.js',
    ],
    theme: {
        extend: {
            colors: {
                surface: 'rgb(var(--c-surface) / <alpha-value>)',
                'surface-dim': 'rgb(var(--c-surface-dim) / <alpha-value>)',
                'surface-bright': 'rgb(var(--c-surface-bright) / <alpha-value>)',
                'surface-container-lowest': 'rgb(var(--c-surface-container-lowest) / <alpha-value>)',
                'surface-container-low': 'rgb(var(--c-surface-container-low) / <alpha-value>)',
                'surface-container': 'rgb(var(--c-surface-container) / <alpha-value>)',
                'surface-container-high': 'rgb(var(--c-surface-container-high) / <alpha-value>)',
                'surface-container-highest': 'rgb(var(--c-surface-container-highest) / <alpha-value>)',
                'on-surface': 'rgb(var(--c-on-surface) / <alpha-value>)',
                'on-surface-variant': 'rgb(var(--c-on-surface-variant) / <alpha-value>)',
                'inverse-surface': 'rgb(var(--c-inverse-surface) / <alpha-value>)',
                'inverse-on-surface': 'rgb(var(--c-inverse-on-surface) / <alpha-value>)',
                outline: 'rgb(var(--c-outline) / <alpha-value>)',
                'outline-variant': 'rgb(var(--c-outline-variant) / <alpha-value>)',
                'surface-tint': 'rgb(var(--c-surface-tint) / <alpha-value>)',
                'surface-variant': 'rgb(var(--c-surface-variant) / <alpha-value>)',
                background: 'rgb(var(--c-background) / <alpha-value>)',
                'on-background': 'rgb(var(--c-on-background) / <alpha-value>)',

                primary: 'rgb(var(--c-primary) / <alpha-value>)',
                'on-primary': 'rgb(var(--c-on-primary) / <alpha-value>)',
                'primary-container': 'rgb(var(--c-primary-container) / <alpha-value>)',
                'on-primary-container': 'rgb(var(--c-on-primary-container) / <alpha-value>)',
                'inverse-primary': 'rgb(var(--c-inverse-primary) / <alpha-value>)',
                'primary-fixed': 'rgb(var(--c-primary-fixed) / <alpha-value>)',
                'primary-fixed-dim': 'rgb(var(--c-primary-fixed-dim) / <alpha-value>)',
                'on-primary-fixed': 'rgb(var(--c-on-primary-fixed) / <alpha-value>)',
                'on-primary-fixed-variant': 'rgb(var(--c-on-primary-fixed-variant) / <alpha-value>)',

                secondary: 'rgb(var(--c-secondary) / <alpha-value>)',
                'on-secondary': 'rgb(var(--c-on-secondary) / <alpha-value>)',
                'secondary-container': 'rgb(var(--c-secondary-container) / <alpha-value>)',
                'on-secondary-container': 'rgb(var(--c-on-secondary-container) / <alpha-value>)',
                'secondary-fixed': 'rgb(var(--c-secondary-fixed) / <alpha-value>)',
                'secondary-fixed-dim': 'rgb(var(--c-secondary-fixed-dim) / <alpha-value>)',
                'on-secondary-fixed': 'rgb(var(--c-on-secondary-fixed) / <alpha-value>)',
                'on-secondary-fixed-variant': 'rgb(var(--c-on-secondary-fixed-variant) / <alpha-value>)',

                tertiary: 'rgb(var(--c-tertiary) / <alpha-value>)',
                'on-tertiary': 'rgb(var(--c-on-tertiary) / <alpha-value>)',
                'tertiary-container': 'rgb(var(--c-tertiary-container) / <alpha-value>)',
                'on-tertiary-container': 'rgb(var(--c-on-tertiary-container) / <alpha-value>)',
                'tertiary-fixed': 'rgb(var(--c-tertiary-fixed) / <alpha-value>)',
                'tertiary-fixed-dim': 'rgb(var(--c-tertiary-fixed-dim) / <alpha-value>)',
                'on-tertiary-fixed': 'rgb(var(--c-on-tertiary-fixed) / <alpha-value>)',
                'on-tertiary-fixed-variant': 'rgb(var(--c-on-tertiary-fixed-variant) / <alpha-value>)',

                error: 'rgb(var(--c-error) / <alpha-value>)',
                'on-error': 'rgb(var(--c-on-error) / <alpha-value>)',
                'error-container': 'rgb(var(--c-error-container) / <alpha-value>)',
                'on-error-container': 'rgb(var(--c-on-error-container) / <alpha-value>)',

                'expense-red': 'rgb(var(--c-expense-red) / <alpha-value>)',
                'expense-bg': 'rgb(var(--c-expense-bg) / <alpha-value>)',
                'income-green': 'rgb(var(--c-income-green) / <alpha-value>)',
                'income-bg': 'rgb(var(--c-income-bg) / <alpha-value>)',
                'slate-muted': 'rgb(var(--c-slate-muted) / <alpha-value>)',
            },
            fontFamily: {
                'display-balance-mobile': ['"Hanken Grotesk"', 'sans-serif'],
                'display-balance': ['"Hanken Grotesk"', 'sans-serif'],
                'headline-section': ['"Hanken Grotesk"', 'sans-serif'],
                'title-item': ['Inter', 'sans-serif'],
                'body-base': ['Inter', 'sans-serif'],
                'body-sm': ['Inter', 'sans-serif'],
                'label-caps': ['"JetBrains Mono"', 'monospace'],
                'stat-label': ['Inter', 'sans-serif'],
            },
            fontSize: {
                'display-balance-mobile': ['36px', { lineHeight: '44px', letterSpacing: '-0.03em', fontWeight: '800' }],
                'display-balance': ['56px', { lineHeight: '64px', letterSpacing: '-0.03em', fontWeight: '800' }],
                'headline-section': ['24px', { lineHeight: '32px', fontWeight: '700' }],
                'title-item': ['18px', { lineHeight: '26px', fontWeight: '600' }],
                'body-base': ['16px', { lineHeight: '24px', fontWeight: '400' }],
                'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
                'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
                'stat-label': ['12px', { lineHeight: '16px', fontWeight: '500' }],
            },
            borderRadius: {
                DEFAULT: '0.25rem',
                lg: '0.5rem',
                xl: '0.75rem',
                '2xl': '1rem',
                '3xl': '1.5rem',
                full: '9999px',
            },
            spacing: {
                xs: '4px',
                sm: '8px',
                md: '16px',
                lg: '24px',
                xl: '32px',
                'margin-mobile': '16px',
                'gutter-mobile': '12px',
            },
        },
    },
    plugins: [],
}
